li =list (map(str,input()))
for i in range(len(li)-1):
    if(li[i]=='1'):print('yi',end=" ")
    if(li[i]=='2'):print('er',end=" ")
    if(li[i]=='3'):print('san',end=" ")
    if(li[i]=='4'):print('si',end=" ")
    if(li[i]=='5'):print('wu',end=" ")
    if(li[i]=='6'):print('liu',end=" ")
    if(li[i]=='7'):print('qi',end=" ")
    if(li[i]=='8'):print('ba',end=" ")
    if(li[i]=='9'):print('jiu',end=" ")
    if(li[i]=='0'):print('ling',end=" ")
    if(li[i]=='-'):print('fu',end=" ")
if(li[len(li)-1]=='1'):print('yi',end="")
if(li[len(li)-1]=='2'):print('er',end="")
if(li[len(li)-1]=='3'):print('san',end="")
if(li[len(li)-1]=='4'):print('si',end="")
if(li[len(li)-1]=='5'):print('wu',end="")
if(li[len(li)-1]=='6'):print('liu',end="")
if(li[len(li)-1]=='7'):print('qi',end="")
if(li[len(li)-1]=='8'):print('ba',end="")
if(li[len(li)-1]=='9'):print('jiu',end="")
if(li[len(li)-1]=='0'):print('ling',end="")
if(li[len(li)-1]=='-'):print('fu',end="")
